
package fr.airpure.main.autoGenerated;

import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
    "nom_dept",
    "nom_com",
    "insee_com",
    "nom_station",
    "code_station",
    "typologie",
    "influence",
    "nom_poll",
    "id_poll_ue",
    "valeur",
    "unite",
    "metrique",
    "date_debut",
    "date_fin",
    "statut_valid",
    "x_l93",
    "y_l93",
    "ObjectId"
})
public class Properties__1 {

    @JsonProperty("nom_dept")
    private String nomDept;
    @JsonProperty("nom_com")
    private String nomCom;
    @JsonProperty("insee_com")
    private Integer inseeCom;
    @JsonProperty("nom_station")
    private String nomStation;
    @JsonProperty("code_station")
    private String codeStation;
    @JsonProperty("typologie")
    private String typologie;
    @JsonProperty("influence")
    private String influence;
    @JsonProperty("nom_poll")
    private String nomPoll;
    @JsonProperty("id_poll_ue")
    private Integer idPollUe;
    @JsonProperty("valeur")
    private Double valeur;
    @JsonProperty("unite")
    private String unite;
    @JsonProperty("metrique")
    private String metrique;
    @JsonProperty("date_debut")
    private String dateDebut;
    @JsonProperty("date_fin")
    private String dateFin;
    @JsonProperty("statut_valid")
    private String statutValid;
    @JsonProperty("x_l93")
    private Integer xL93;
    @JsonProperty("y_l93")
    private Integer yL93;
    @JsonProperty("ObjectId")
    private Integer objectId;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    @JsonProperty("nom_dept")
    public String getNomDept() {
        return nomDept;
    }

    @JsonProperty("nom_dept")
    public void setNomDept(String nomDept) {
        this.nomDept = nomDept;
    }

    @JsonProperty("nom_com")
    public String getNomCom() {
        return nomCom;
    }

    @JsonProperty("nom_com")
    public void setNomCom(String nomCom) {
        this.nomCom = nomCom;
    }

    @JsonProperty("insee_com")
    public Integer getInseeCom() {
        return inseeCom;
    }

    @JsonProperty("insee_com")
    public void setInseeCom(Integer inseeCom) {
        this.inseeCom = inseeCom;
    }

    @JsonProperty("nom_station")
    public String getNomStation() {
        return nomStation;
    }

    @JsonProperty("nom_station")
    public void setNomStation(String nomStation) {
        this.nomStation = nomStation;
    }

    @JsonProperty("code_station")
    public String getCodeStation() {
        return codeStation;
    }

    @JsonProperty("code_station")
    public void setCodeStation(String codeStation) {
        this.codeStation = codeStation;
    }

    @JsonProperty("typologie")
    public String getTypologie() {
        return typologie;
    }

    @JsonProperty("typologie")
    public void setTypologie(String typologie) {
        this.typologie = typologie;
    }

    @JsonProperty("influence")
    public String getInfluence() {
        return influence;
    }

    @JsonProperty("influence")
    public void setInfluence(String influence) {
        this.influence = influence;
    }

    @JsonProperty("nom_poll")
    public String getNomPoll() {
        return nomPoll;
    }

    @JsonProperty("nom_poll")
    public void setNomPoll(String nomPoll) {
        this.nomPoll = nomPoll;
    }

    @JsonProperty("id_poll_ue")
    public Integer getIdPollUe() {
        return idPollUe;
    }

    @JsonProperty("id_poll_ue")
    public void setIdPollUe(Integer idPollUe) {
        this.idPollUe = idPollUe;
    }

    @JsonProperty("valeur")
    public Double getValeur() {
        return valeur;
    }

    @JsonProperty("valeur")
    public void setValeur(Double valeur) {
        this.valeur = valeur;
    }

    @JsonProperty("unite")
    public String getUnite() {
        return unite;
    }

    @JsonProperty("unite")
    public void setUnite(String unite) {
        this.unite = unite;
    }

    @JsonProperty("metrique")
    public String getMetrique() {
        return metrique;
    }

    @JsonProperty("metrique")
    public void setMetrique(String metrique) {
        this.metrique = metrique;
    }

    @JsonProperty("date_debut")
    public String getDateDebut() {
        return dateDebut;
    }

    @JsonProperty("date_debut")
    public void setDateDebut(String dateDebut) {
        this.dateDebut = dateDebut;
    }

    @JsonProperty("date_fin")
    public String getDateFin() {
        return dateFin;
    }

    @JsonProperty("date_fin")
    public void setDateFin(String dateFin) {
        this.dateFin = dateFin;
    }

    @JsonProperty("statut_valid")
    public String getStatutValid() {
        return statutValid;
    }

    @JsonProperty("statut_valid")
    public void setStatutValid(String statutValid) {
        this.statutValid = statutValid;
    }

    @JsonProperty("x_l93")
    public Integer getxL93() {
        return xL93;
    }

    @JsonProperty("x_l93")
    public void setxL93(Integer xL93) {
        this.xL93 = xL93;
    }

    @JsonProperty("y_l93")
    public Integer getyL93() {
        return yL93;
    }

    @JsonProperty("y_l93")
    public void setyL93(Integer yL93) {
        this.yL93 = yL93;
    }

    @JsonProperty("ObjectId")
    public Integer getObjectId() {
        return objectId;
    }

    @JsonProperty("ObjectId")
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(Properties__1 .class.getName()).append('@').append(Integer.toHexString(System.identityHashCode(this))).append('[');
        sb.append("nomDept");
        sb.append('=');
        sb.append(((this.nomDept == null)?"<null>":this.nomDept));
        sb.append(',');
        sb.append("nomCom");
        sb.append('=');
        sb.append(((this.nomCom == null)?"<null>":this.nomCom));
        sb.append(',');
        sb.append("inseeCom");
        sb.append('=');
        sb.append(((this.inseeCom == null)?"<null>":this.inseeCom));
        sb.append(',');
        sb.append("nomStation");
        sb.append('=');
        sb.append(((this.nomStation == null)?"<null>":this.nomStation));
        sb.append(',');
        sb.append("codeStation");
        sb.append('=');
        sb.append(((this.codeStation == null)?"<null>":this.codeStation));
        sb.append(',');
        sb.append("typologie");
        sb.append('=');
        sb.append(((this.typologie == null)?"<null>":this.typologie));
        sb.append(',');
        sb.append("influence");
        sb.append('=');
        sb.append(((this.influence == null)?"<null>":this.influence));
        sb.append(',');
        sb.append("nomPoll");
        sb.append('=');
        sb.append(((this.nomPoll == null)?"<null>":this.nomPoll));
        sb.append(',');
        sb.append("idPollUe");
        sb.append('=');
        sb.append(((this.idPollUe == null)?"<null>":this.idPollUe));
        sb.append(',');
        sb.append("valeur");
        sb.append('=');
        sb.append(((this.valeur == null)?"<null>":this.valeur));
        sb.append(',');
        sb.append("unite");
        sb.append('=');
        sb.append(((this.unite == null)?"<null>":this.unite));
        sb.append(',');
        sb.append("metrique");
        sb.append('=');
        sb.append(((this.metrique == null)?"<null>":this.metrique));
        sb.append(',');
        sb.append("dateDebut");
        sb.append('=');
        sb.append(((this.dateDebut == null)?"<null>":this.dateDebut));
        sb.append(',');
        sb.append("dateFin");
        sb.append('=');
        sb.append(((this.dateFin == null)?"<null>":this.dateFin));
        sb.append(',');
        sb.append("statutValid");
        sb.append('=');
        sb.append(((this.statutValid == null)?"<null>":this.statutValid));
        sb.append(',');
        sb.append("xL93");
        sb.append('=');
        sb.append(((this.xL93 == null)?"<null>":this.xL93));
        sb.append(',');
        sb.append("yL93");
        sb.append('=');
        sb.append(((this.yL93 == null)?"<null>":this.yL93));
        sb.append(',');
        sb.append("objectId");
        sb.append('=');
        sb.append(((this.objectId == null)?"<null>":this.objectId));
        sb.append(',');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.valeur == null)? 0 :this.valeur.hashCode()));
        result = ((result* 31)+((this.unite == null)? 0 :this.unite.hashCode()));
        result = ((result* 31)+((this.nomDept == null)? 0 :this.nomDept.hashCode()));
        result = ((result* 31)+((this.typologie == null)? 0 :this.typologie.hashCode()));
        result = ((result* 31)+((this.statutValid == null)? 0 :this.statutValid.hashCode()));
        result = ((result* 31)+((this.influence == null)? 0 :this.influence.hashCode()));
        result = ((result* 31)+((this.metrique == null)? 0 :this.metrique.hashCode()));
        result = ((result* 31)+((this.dateDebut == null)? 0 :this.dateDebut.hashCode()));
        result = ((result* 31)+((this.yL93 == null)? 0 :this.yL93 .hashCode()));
        result = ((result* 31)+((this.nomCom == null)? 0 :this.nomCom.hashCode()));
        result = ((result* 31)+((this.nomPoll == null)? 0 :this.nomPoll.hashCode()));
        result = ((result* 31)+((this.inseeCom == null)? 0 :this.inseeCom.hashCode()));
        result = ((result* 31)+((this.nomStation == null)? 0 :this.nomStation.hashCode()));
        result = ((result* 31)+((this.idPollUe == null)? 0 :this.idPollUe.hashCode()));
        result = ((result* 31)+((this.codeStation == null)? 0 :this.codeStation.hashCode()));
        result = ((result* 31)+((this.xL93 == null)? 0 :this.xL93 .hashCode()));
        result = ((result* 31)+((this.dateFin == null)? 0 :this.dateFin.hashCode()));
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        result = ((result* 31)+((this.objectId == null)? 0 :this.objectId.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof Properties__1) == false) {
            return false;
        }
        Properties__1 rhs = ((Properties__1) other);
        return ((((((((((((((((((((this.valeur == rhs.valeur)||((this.valeur!= null)&&this.valeur.equals(rhs.valeur)))&&((this.unite == rhs.unite)||((this.unite!= null)&&this.unite.equals(rhs.unite))))&&((this.nomDept == rhs.nomDept)||((this.nomDept!= null)&&this.nomDept.equals(rhs.nomDept))))&&((this.typologie == rhs.typologie)||((this.typologie!= null)&&this.typologie.equals(rhs.typologie))))&&((this.statutValid == rhs.statutValid)||((this.statutValid!= null)&&this.statutValid.equals(rhs.statutValid))))&&((this.influence == rhs.influence)||((this.influence!= null)&&this.influence.equals(rhs.influence))))&&((this.metrique == rhs.metrique)||((this.metrique!= null)&&this.metrique.equals(rhs.metrique))))&&((this.dateDebut == rhs.dateDebut)||((this.dateDebut!= null)&&this.dateDebut.equals(rhs.dateDebut))))&&((this.yL93 == rhs.yL93)||((this.yL93 != null)&&this.yL93 .equals(rhs.yL93))))&&((this.nomCom == rhs.nomCom)||((this.nomCom!= null)&&this.nomCom.equals(rhs.nomCom))))&&((this.nomPoll == rhs.nomPoll)||((this.nomPoll!= null)&&this.nomPoll.equals(rhs.nomPoll))))&&((this.inseeCom == rhs.inseeCom)||((this.inseeCom!= null)&&this.inseeCom.equals(rhs.inseeCom))))&&((this.nomStation == rhs.nomStation)||((this.nomStation!= null)&&this.nomStation.equals(rhs.nomStation))))&&((this.idPollUe == rhs.idPollUe)||((this.idPollUe!= null)&&this.idPollUe.equals(rhs.idPollUe))))&&((this.codeStation == rhs.codeStation)||((this.codeStation!= null)&&this.codeStation.equals(rhs.codeStation))))&&((this.xL93 == rhs.xL93)||((this.xL93 != null)&&this.xL93 .equals(rhs.xL93))))&&((this.dateFin == rhs.dateFin)||((this.dateFin!= null)&&this.dateFin.equals(rhs.dateFin))))&&((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)&&this.additionalProperties.equals(rhs.additionalProperties))))&&((this.objectId == rhs.objectId)||((this.objectId!= null)&&this.objectId.equals(rhs.objectId))));
    }

}
