package fr.airpure.main.utils;

import java.util.Comparator;

import fr.airpure.main.autoGenerated.Feature;
import fr.airpure.main.autoGenerated.Properties__1;
import fr.airpure.main.entities.Polluant;

public class PropertiesComparator implements Comparator<Properties__1> {
    @Override
    public int compare(Properties__1 p1, Properties__1 p2) {
        return p1.getDateFin().compareTo(p2.getDateFin());
    }
}