package fr.airpure.main.services;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import fr.airpure.main.autoGenerated.Feature;
import fr.airpure.main.autoGenerated.ApiPollutionResponse;
import fr.airpure.main.entities.Commune;
import fr.airpure.main.entities.Polluant;
import fr.airpure.main.entities.Station;
import fr.airpure.main.exceptions.echange.NotFoundException;

@Service
public class ExtractPolluantService {
	private static final Logger LOG = LoggerFactory.getLogger(ExtractPolluantService.class);
	private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss"); 
	private static final String PATH_ATMO = "https://opendata.arcgis.com/datasets/4a648b54876f485e92f22e2ad5a5da32_0.geojson";
	
	
	private CommuneService communeService;
	private StationService stationService;
	private PolluantService polluantService;
	
	public ExtractPolluantService(CommuneService communeService, StationService stationService,  PolluantService polluantService) {
		this.communeService = communeService;
		this.stationService = stationService;
		this.polluantService = polluantService;
	}
	
	
	public void extract(RestTemplate restTemplate) {
			List<Feature> maListe = this.getDatasFromAtmo(restTemplate);
			long start = System.currentTimeMillis();
			LOG.info("Debut de la lecture du fichier JSON");
			for (Feature m : maListe) {
				LOG.info("Formattage des dates terminés");
				try {
					// POUR CHAQUE LIGNE JE CREAIS UN POLLUANT ET UNE STATION
					// JE CHERCHE LA REGION PAR CODE INSEE DE LA COMMUNE TRAITEE
					// Region region = this.regionService.findByCodeInsee(String.valueOf(m.getProperties().getInseeCom()));
					String codeInsee = String.valueOf(m.getProperties().getInseeCom());
					Commune commune = this.communeService.findByCodeInsee(codeInsee);
					// JE CONVERTIS LES DATE
					LocalDateTime dateDebutFinale = this.parseAndConverte(m.getProperties().getDateDebut());
					LocalDateTime dateFinFinale = this.parseAndConverte(m.getProperties().getDateFin());
					// CREATION STATION
					Station station = this.stationService.creer(m);
					// JOINTURE STATION COMMUNE
					station.setCommune(commune);
					//PERSIST STATION
					Station stationDataBase = this.stationService.save(station);
					LOG.info("Station créée et persistées");
					// CREATION POLLUANT
					Polluant polluant = this.polluantService.creer(m, dateDebutFinale, dateFinFinale);
					// JOINTURE POLLUANT STATION
					polluant.setStation(stationDataBase);
					// PERSIST POLLUANT
					this.polluantService.save(polluant);
					LOG.info("Polluant créé et persistés");
				} catch (NotFoundException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				} 
				
			}
			long tempsExecution = System.currentTimeMillis() - start;
			LOG.info("Fin du programme");
			LOG.info("--------------------------------------");
			LOG.info("Temps d'execution " + tempsExecution);
	}
	
	/**
	 * Enleve les millisecondes de la date et converti en LocalDateTime
	 * @param dateAtraiter
	 * @return
	 */
	public LocalDateTime parseAndConverte(String dateAtraiter) {
		String date = this.parseDate(dateAtraiter);
		return LocalDateTime.parse(date, FORMATTER);
	}
	
	/**
	 * A MODIFIER
	 */
	public LocalDateTime parseAndConverteForcaste(String dateAtraiter) {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"); 
		String date = this.parseDate(dateAtraiter);
		String newDate = date.replace("T", " ");
		return LocalDateTime.parse(newDate, formatter);
	}
	
	/**
	 * Recupere les données de qualité d'air du site Atmo
	 * @param restTemplate
	 * @return
	 */
	private List<Feature> getDatasFromAtmo(RestTemplate restTemplate) {
		ApiPollutionResponse qualiteAirListe = restTemplate.getForObject(PATH_ATMO, ApiPollutionResponse.class);
		return qualiteAirListe.getFeatures();
	}
	
	/**
	 * LA DATE ARRIVE AVEC LES MILLISECONDES AU FORMAT 
	 * 2021/01/10 21:00:00+00
	 * JE LA VEUX EN 2021/01/10 21:00:00
	 * @param date
	 * @return
	 */
	private String parseDate(String dateAtraiter) {
		Integer indexFin = dateAtraiter.indexOf("+");
		return dateAtraiter.substring(0, indexFin);
	}
	
	public List<Commune> getTop50Population()  {
		return this.communeService.getTop50Population();
	}
}
