package fr.airpure.main.services;

import org.springframework.stereotype.Service;

import fr.airpure.main.autoGenerated.Feature;
import fr.airpure.main.entities.Station;
import fr.airpure.main.repositories.StationRepository;

@Service
public class StationService {
	private StationRepository stationRepository;
	
	public StationService(StationRepository stationRepository) {
		this.stationRepository = stationRepository;
	}
	
	public Station creer(Feature m) {
		return new Station(m.getProperties().getNomStation(), 
				String.valueOf(m.getProperties().getyL93()), 
				String.valueOf(m.getProperties().getxL93()));
	}
	
	public Station save(Station station) {
		return this.stationRepository.save(station);
	}
}
