package fr.airpure.main.services;

import java.util.List;
import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import fr.airpure.main.autoGenerated.Feature;
import fr.airpure.main.entities.Station;
import fr.airpure.main.repositories.StationRepository;

@Service
public class StationService {
	@Autowired
	private StationRepository stationRepository;
	
	public StationService() {
	
	}
	
	public List<Station> getStations() {
		return this.stationRepository.findAll();
		
	}
	public Station creer(Feature m) {
		return new Station(m.getProperties().getNomStation(), 
							String.valueOf(m.getProperties().getyL93()), 
							String.valueOf(m.getProperties().getxL93()));
	}
	
	public Station save(Station station) {
		return this.stationRepository.save(station);
	}
	
	public boolean checkExistenceStationBDD(String nomStation) {
		if ( this.stationRepository.findByNom(nomStation).isPresent() ) {
			return true;
		} else {
			return false;
		}
	}
	
	public Optional<Station> getStationByNom(String nomStation) {
		return  this.stationRepository.findByNom(nomStation);
	}
}
